# Generated by Django 4.2.4 on 2023-08-25 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='food_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
